# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meroxa < Formula
  desc "The Meroxa CLI"
  homepage "https://meroxa.io"
  version "0.3.4"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/raulb/cli/releases/download/v0.3.4/meroxa_0.3.4_Darwin_x86_64.tar.gz"
    sha256 "716f5b772da49ebeb493bec6d7f8ea83e0d968de5b90e6ee961e39a87bb18dcb"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/raulb/cli/releases/download/v0.3.4/meroxa_0.3.4_Darwin_arm64.tar.gz"
    sha256 "1b75b52ebd3bb045f07a3db35c56e5e77c972e1bdfaf17de744b31299aaed9f7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/raulb/cli/releases/download/v0.3.4/meroxa_0.3.4_Linux_x86_64.tar.gz"
    sha256 "f9b9366ede0a9574ada3d77813fc7dfe00c1a7a647cd8d1caf3552e55baab4a8"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/raulb/cli/releases/download/v0.3.4/meroxa_0.3.4_Linux_arm64.tar.gz"
    sha256 "ee3265a590bb050dc0f82242d5918250bec6e25ed7b22967b39a772549bd79d0"
  end

  head "https://github.com/raulb/cli.git"

  def install
    bin.install "meroxa"
    prefix.install_metafiles
    bash_completion.install "etc/completion/meroxa.completion.sh"
    zsh_completion.install "etc/completion/meroxa.completion.zsh" => "meroxa"
    fish_completion.install "etc/completion/meroxa.completion.fish"
    man.install "etc/man/man1"
  end

  test do
    shell_output("#{bin}/meroxa version").match(/0.3.4/)
  end
end
