# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meroxa < Formula
  desc "The Meroxa CLI"
  homepage "https://meroxa.io"
  version "0.3.4"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/raulb/cli/releases/download/v0.3.4/meroxa_0.3.4_Darwin_x86_64.tar.gz"
    sha256 "a4d2ce313cb25c98134bd62ff9e8ad9b0dcbedc60530d350a0c49fb6eab97d5a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/raulb/cli/releases/download/v0.3.4/meroxa_0.3.4_Darwin_arm64.tar.gz"
    sha256 "ab373812ba2126dd8ec7f6271d55574e04c98df27d4274e3acb0feb2b39cc53b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/raulb/cli/releases/download/v0.3.4/meroxa_0.3.4_Linux_x86_64.tar.gz"
    sha256 "6897785f77534fbff2d91dbac521b84d695a1f909d1fcd4f6025fe4be9c2916c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/raulb/cli/releases/download/v0.3.4/meroxa_0.3.4_Linux_arm64.tar.gz"
    sha256 "9138b0494e30dc05740b3664dbf584cf9caf505261cb947791616178ed585329"
  end

  head "https://github.com/raulb/cli.git"

  def install
    bin.install "meroxa"
    bash_completion.install "etc/completion/meroxa.completion.sh"
    zsh_completion.install "etc/completion/meroxa.completion.zsh" => "meroxa"
    fish_completion.install "etc/completion/meroxa.completion.fish"
    man.install "etc/man/man1"
  end

  test do
    shell_output("#{bin}/meroxa version").match(/0.3.4/)
  end
end
